langauge: c
compiler:
 - clang
 - gcc
install: bash ./get-deps.sh

script:
 - mkdir build
 - cd build
 - cmake ..
 - cmake --build .

cache:
  directories:
    - ./deps

before_scipt: ./deps/cpplint.py