language: c
python:
  - "2.7"

sudo: required
dist: trusty

compiler:
 - gcc

install: bash ./scripts/get-deps.sh

env:
  global:
    - CTEST_EXT_COLOR_OUTPUT=TRUE
    - CTEST_BUILD_FLAGS=-j4

script:
 - mkdir build
 - cd build
 - cmake ..
 - cmake --build .
 - ctest -VV

after_success:
  - coveralls -e 'test' -e 'src/simplify.c' --root .. --gcov-options '\-lp'

addons:
  apt:
    packages:
      - valgrind

before_install:
  - pip install --user cpp-coveralls

cache:
  directories:
    - ./deps